#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Canvas shadow_read 就绪度合成负载评估探针（synthetic load · 非真实生产观察）。

用途
====

Wave 3-K 数据 PR-10(`CANVAS_PRIMARY_WRITE=db` 显式启用)前置的**合成负载
就绪度评估**工具。

**严格声明**：本探针产出的一切指标**都不是真实生产观察**——真实
`data/canvas/*.json` 为 0、`canvases` 表在生产 DB 未建、`SHADOW_READ_CANVAS`
env 也从未在窗口内 truthy。本工具通过在**独立 tmp workspace** 里合成 N 个
mock canvas + 独立 SQLite（`tmp_path/shadow.db`）+ 独立 CANVAS_DIR + 独立
shadow_diff dir，跑 4 个场景采数，输出**合成负载就绪度**指标。

零污染保证
==========

- 不改动 `data/canvas/` 内任何真实 canvas JSON。
- 不改动 `data/app.db` 内任何生产表；所有 DB 操作走独立 SQLite。
- 不改动 `data/shadow_diff/canvas/` 内任何真实 shadow diff；合成路径落到
  `<tmp_path>/shadow_diff/`。
- 完全走 `monkeypatch` pattern 的手动实现（`_isolated_workspace`）——每次
  调用后 `main` 模块的 attribute + `app.db.engine` singleton 都 restore。

CLI
===

::

    python -m tools.synth_shadow_read_probe --scale=50 --output=/tmp/probe.json
    python -m tools.synth_shadow_read_probe --scale=200 --output=./probe-200.json
    python -m tools.synth_shadow_read_probe --scale=10 --output=./probe-10.json

- ``--scale``: 合成 canvas 数量，允许 10 / 50 / 200 / 500，默认 50
- ``--output``: JSON 报告输出路径（必需）
- ``--seed``: 随机种子（默认 1337，保证可重现）
- ``--loads``: 场景 A/B 的 load 次数（默认 100）
- ``--saves``: 场景 C 的 save 次数（默认 200）
- ``--tx-fail-iters``: 场景 D 的 shadow write 失败注入次数（默认 3）

产出
====

一个 JSON 对象，key:

- ``schema``: 稳定键位版本（``synth-probe/v1``）
- ``synthetic_load_declaration``: 显式声明本工具非真实生产观察
- ``scale``: 采样 canvas 数量
- ``environment``: 环境事实核查
- ``scenarios``: 4 个场景 × 各指标
- ``observations``: 观察到的异常 / CB-P5-08 候选描述

治理规范
========

本工具对齐 Wave 3-K 任务书；下游 `docs/ops-reports/*-synthetic-load-*.md`
应引用本工具产出的 JSON 作为事实依据。**探针不 commit 到 origin/main
必须由 Lead 白名单 commit**（Wave 3-J GM-12 交付边界硬约束）。
"""

from __future__ import annotations

import argparse
import contextlib
import datetime as _dt
import json
import os
import random
import sqlite3
import statistics
import sys
import time
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


SCHEMA_VERSION = "synth-probe/v1"
SYNTHETIC_DECLARATION = (
    "synthetic load only · NOT a real production observation · "
    "generated by tools.synth_shadow_read_probe · Wave 3-K readiness evaluation"
)


# ---------------------------------------------------------------------------
# environment fact-check
# ---------------------------------------------------------------------------


def _environment_fact_check() -> dict[str, Any]:
    """核查真实 data/canvas / canvases 表 / shadow_diff 状态；只读，不改。"""

    facts: dict[str, Any] = {}

    canvas_dir = REPO_ROOT / "data" / "canvas"
    facts["data/canvas exists"] = canvas_dir.exists()
    if canvas_dir.exists():
        facts["data/canvas *.json count"] = len(list(canvas_dir.glob("*.json")))
    else:
        facts["data/canvas *.json count"] = 0

    canvases_dir = REPO_ROOT / "data" / "canvases"
    facts["data/canvases exists"] = canvases_dir.exists()
    if canvases_dir.exists():
        facts["data/canvases *.json count"] = len(list(canvases_dir.glob("*.json")))

    db_path = REPO_ROOT / "data" / "app.db"
    facts["data/app.db exists"] = db_path.exists()
    if db_path.exists():
        try:
            conn = sqlite3.connect(str(db_path))
            try:
                row = conn.execute(
                    "SELECT name FROM sqlite_master WHERE type='table' AND name='canvases'"
                ).fetchone()
                facts["canvases table exists in prod DB"] = bool(row)
                if row:
                    n = conn.execute("SELECT COUNT(*) FROM canvases").fetchone()[0]
                    facts["canvases table row count"] = int(n)
            finally:
                conn.close()
        except Exception as exc:  # pragma: no cover
            facts["canvases table probe error"] = str(exc)

    shadow_diff_canvas = REPO_ROOT / "data" / "shadow_diff" / "canvas"
    facts["data/shadow_diff/canvas exists"] = shadow_diff_canvas.exists()
    if shadow_diff_canvas.exists():
        facts["data/shadow_diff/canvas jsonl count"] = len(
            list(shadow_diff_canvas.glob("*.jsonl"))
        )

    return facts


# ---------------------------------------------------------------------------
# isolated workspace (manual monkeypatch equivalent)
# ---------------------------------------------------------------------------


@contextlib.contextmanager
def _isolated_workspace(tmp_path: Path):
    """把 main.DATA_DIR / CANVAS_DIR / DATA_DB_PATH 指向 tmp_path。

    对应 `tests/shadow_read/_helpers.py::isolated_shadow_env` 的 pytest fixture
    实现，但走 setattr/restore 手工模式，可在 CLI 里使用。
    """

    import main
    from app.db import engine as db_engine
    from app.db import session as db_session

    saved = {
        "DATA_DIR": main.DATA_DIR,
        "CANVAS_DIR": main.CANVAS_DIR,
        "DATA_DB_PATH": main.DATA_DB_PATH,
    }
    canvas_dir = tmp_path / "canvases"
    canvas_dir.mkdir(parents=True, exist_ok=True)

    main.DATA_DIR = str(tmp_path)
    main.CANVAS_DIR = str(canvas_dir)
    main.DATA_DB_PATH = str(tmp_path / "shadow.db")
    db_engine.reset_engine()
    db_session._SessionLocal = None

    try:
        yield tmp_path
    finally:
        main.DATA_DIR = saved["DATA_DIR"]
        main.CANVAS_DIR = saved["CANVAS_DIR"]
        main.DATA_DB_PATH = saved["DATA_DB_PATH"]
        db_engine.reset_engine()
        db_session._SessionLocal = None


@contextlib.contextmanager
def _env_scope(env: dict[str, str | None]):
    """临时 set/unset env vars；退出时 restore。"""

    saved: dict[str, str | None] = {k: os.environ.get(k) for k in env}
    for k, v in env.items():
        if v is None:
            os.environ.pop(k, None)
        else:
            os.environ[k] = v
    try:
        yield
    finally:
        for k, v in saved.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v


# ---------------------------------------------------------------------------
# synthetic canvas factory
# ---------------------------------------------------------------------------


def _make_synthetic_canvas(rng: random.Random, canvas_id: str) -> dict[str, Any]:
    """造一个 mock canvas；nodes/connections 数量 5-30 随机。"""

    n_nodes = rng.randint(5, 30)
    n_conns = rng.randint(5, 30)
    now_ms = int(time.time() * 1000)
    return {
        "id": canvas_id,
        "title": f"Synthetic Canvas {canvas_id}",
        "kind": rng.choice(["classic", "smart"]),
        "project": "synth-default",
        "owner": "synth-probe",
        "pinned": rng.choice([True, False]),
        "created_at": now_ms - rng.randint(0, 86400 * 1000),
        "updated_at": now_ms,
        "deleted_at": None,
        "revision": rng.randint(0, 5),
        "base_updated_at": None,
        "nodes": [
            {"id": f"n{i}", "type": "generator", "x": i * 10, "y": i * 20}
            for i in range(n_nodes)
        ],
        "connections": [
            {"from": f"n{i}", "to": f"n{(i + 1) % max(n_nodes, 1)}"}
            for i in range(n_conns)
        ],
    }


def _write_canvas_json(canvas: dict[str, Any], canvas_dir: Path) -> None:
    path = canvas_dir / f"{canvas['id']}.json"
    path.write_text(json.dumps(canvas, ensure_ascii=False, indent=2), encoding="utf-8")


def _percentiles(values: list[float]) -> dict[str, float]:
    if not values:
        return {"p50_ms": 0.0, "p95_ms": 0.0, "p99_ms": 0.0, "max_ms": 0.0, "count": 0}
    sorted_v = sorted(values)
    n = len(sorted_v)

    def _pct(p: float) -> float:
        if n == 1:
            return sorted_v[0]
        k = (n - 1) * p
        f = int(k)
        c = min(f + 1, n - 1)
        return sorted_v[f] + (sorted_v[c] - sorted_v[f]) * (k - f)

    return {
        "p50_ms": round(_pct(0.50) * 1000, 3),
        "p95_ms": round(_pct(0.95) * 1000, 3),
        "p99_ms": round(_pct(0.99) * 1000, 3),
        "max_ms": round(sorted_v[-1] * 1000, 3),
        "count": n,
    }


# ---------------------------------------------------------------------------
# scenarios
# ---------------------------------------------------------------------------


def _seed_canvases_json(
    canvas_dir: Path, rng: random.Random, scale: int
) -> list[dict[str, Any]]:
    """写 N 个 mock canvas JSON 到 canvas_dir；返回全部 dict list。"""

    canvases: list[dict[str, Any]] = []
    for i in range(scale):
        canvas_id = f"synth_c_{i:05d}"
        c = _make_synthetic_canvas(rng, canvas_id)
        _write_canvas_json(c, canvas_dir)
        canvases.append(c)
    return canvases


def _import_all_to_db(canvas_dir: Path) -> int:
    """把 canvas_dir 全导 DB；返回 inserted 数量。"""

    from app.data_import import import_domain
    from tests.shadow_read._helpers import migrate_baseline

    migrate_baseline(canvas_dir.parent)
    outcome = import_domain("canvas", source_path=str(canvas_dir), dry_run=False)
    return int(outcome.inserted)


def _import_partial_to_db(canvas_dir: Path, keep_ids: set[str]) -> int:
    """选择性导入 DB：只导 keep_ids 中的 canvas。做法：临时目录只放 keep_ids。"""

    from app.data_import import import_domain
    from tests.shadow_read._helpers import migrate_baseline

    migrate_baseline(canvas_dir.parent)
    # 造一个临时子目录，只放要导的
    subset_dir = canvas_dir.parent / "subset_import"
    subset_dir.mkdir(parents=True, exist_ok=True)
    for cid in keep_ids:
        src = canvas_dir / f"{cid}.json"
        if src.exists():
            (subset_dir / f"{cid}.json").write_text(
                src.read_text(encoding="utf-8"), encoding="utf-8"
            )
    outcome = import_domain("canvas", source_path=str(subset_dir), dry_run=False)
    return int(outcome.inserted)


def _scenario_A_hit_rate(
    canvas_dir: Path,
    canvases: list[dict[str, Any]],
    rng: random.Random,
    loads: int,
) -> dict[str, Any]:
    """场景 A：N 个双写；100 次随机 load；期望 missing_in_db 全空。"""

    from app.stores import canvas_store

    inserted = _import_all_to_db(canvas_dir)
    all_ids = [c["id"] for c in canvases]

    hits = 0
    misses = 0
    field_diff_counts: list[int] = []
    load_latency: list[float] = []

    with _env_scope(
        {"SHADOW_READ_CANVAS": "true", "CANVAS_PRIMARY_WRITE": "json"}
    ):
        for _ in range(loads):
            cid = rng.choice(all_ids)
            t0 = time.perf_counter()
            try:
                canvas_store.load_canvas(cid)
            except Exception:
                # HTTPException from 404 shouldn't occur here (all files exist)
                misses += 1
                continue
            load_latency.append(time.perf_counter() - t0)

    # 读回 shadow_diff/canvas/*.jsonl 统计
    diff_root = canvas_dir.parent / "shadow_diff" / "canvas"
    lines: list[dict[str, Any]] = []
    if diff_root.exists():
        for f in diff_root.glob("*.jsonl"):
            for line in f.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    lines.append(json.loads(line))
                except Exception:
                    pass

    hits_no_missing_in_db = sum(1 for rec in lines if not rec.get("missing_in_db"))
    records_with_missing_in_db = sum(1 for rec in lines if rec.get("missing_in_db"))
    records_with_missing_in_json = sum(
        1 for rec in lines if rec.get("missing_in_json")
    )
    total = len(lines)
    for rec in lines:
        field_diff_counts.append(len(rec.get("field_diffs", [])))

    return {
        "description": (
            "N canvas 全部 JSON + DB 双写；100 次随机 load；"
            "期望 missing_in_db 全空（field_diffs 会因 created_at/updated_at 类型转换非零，属既知行为）"
        ),
        "db_inserted": inserted,
        "loads_attempted": loads,
        "shadow_diff_records_written": total,
        "records_with_missing_in_db_empty": hits_no_missing_in_db,
        "records_with_missing_in_db_nonempty": records_with_missing_in_db,
        "records_with_missing_in_json_nonempty": records_with_missing_in_json,
        "hit_rate": (
            round(hits_no_missing_in_db / total, 4) if total > 0 else None
        ),
        "field_diff_count_stats": {
            "mean": (
                round(sum(field_diff_counts) / len(field_diff_counts), 2)
                if field_diff_counts
                else 0.0
            ),
            "max": max(field_diff_counts) if field_diff_counts else 0,
        },
        "load_latency": _percentiles(load_latency),
        "target_hit_rate": ">= 0.99",
        "verdict": (
            "PASS"
            if total > 0 and hits_no_missing_in_db / total >= 0.99
            else "FAIL"
        ),
    }


def _scenario_B_diff_rate(
    canvas_dir: Path,
    canvases: list[dict[str, Any]],
    rng: random.Random,
    loads: int,
) -> dict[str, Any]:
    """场景 B：N JSON 全写；DB 只写 90%；100 次随机 load；期望 ~10% missing_in_db。"""

    from app.stores import canvas_store

    all_ids = [c["id"] for c in canvases]
    keep_count = max(1, int(round(len(all_ids) * 0.9)))
    keep_ids = set(rng.sample(all_ids, k=keep_count))
    missing_ids = set(all_ids) - keep_ids

    inserted = _import_partial_to_db(canvas_dir, keep_ids)

    loads_missing_expected = 0
    loads_hit_expected = 0

    with _env_scope(
        {"SHADOW_READ_CANVAS": "true", "CANVAS_PRIMARY_WRITE": "json"}
    ):
        for _ in range(loads):
            cid = rng.choice(all_ids)
            if cid in missing_ids:
                loads_missing_expected += 1
            else:
                loads_hit_expected += 1
            try:
                canvas_store.load_canvas(cid)
            except Exception:
                pass

    diff_root = canvas_dir.parent / "shadow_diff" / "canvas"
    lines: list[dict[str, Any]] = []
    if diff_root.exists():
        for f in diff_root.glob("*.jsonl"):
            for line in f.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    lines.append(json.loads(line))
                except Exception:
                    pass

    records_with_missing_in_db = sum(1 for rec in lines if rec.get("missing_in_db"))
    total = len(lines)

    diff_rate = round(records_with_missing_in_db / total, 4) if total > 0 else None
    expected_ratio = round(loads_missing_expected / loads, 4) if loads > 0 else None

    return {
        "description": (
            "N JSON 全写；DB 90% (缺 10%)；100 次随机 load；"
            "期望 shadow diff 中 ~10% 记录含 missing_in_db"
        ),
        "keep_ratio_target": 0.9,
        "db_inserted": inserted,
        "missing_ids_count": len(missing_ids),
        "loads_attempted": loads,
        "loads_landed_on_missing": loads_missing_expected,
        "loads_landed_on_hit": loads_hit_expected,
        "expected_diff_rate": expected_ratio,
        "shadow_diff_records_written": total,
        "records_with_missing_in_db_nonempty": records_with_missing_in_db,
        "observed_diff_rate": diff_rate,
        "delta_vs_expected": (
            round(abs((diff_rate or 0.0) - (expected_ratio or 0.0)), 4)
            if diff_rate is not None and expected_ratio is not None
            else None
        ),
        "target_delta_bound": "<= 0.05",
        "verdict": (
            "PASS"
            if diff_rate is not None
            and expected_ratio is not None
            and abs(diff_rate - expected_ratio) <= 0.05
            else "FAIL"
        ),
    }


def _scenario_C_write_latency(
    canvas_dir: Path,
    canvases: list[dict[str, Any]],
    rng: random.Random,
    saves: int,
) -> dict[str, Any]:
    """场景 C：save_canvas 循环 200 次（SHADOW_WRITE_CANVAS enable）；测 P50/P95/P99。"""

    from app.stores import canvas_store
    from tests.shadow_read._helpers import migrate_baseline

    migrate_baseline(canvas_dir.parent)

    # 先给 canvas_store 一批 seed（复用 seeded canvases）
    save_latency: list[float] = []
    errors_bubbled = 0

    with _env_scope(
        {"SHADOW_WRITE_CANVAS": "true", "CANVAS_PRIMARY_WRITE": "json"}
    ):
        for i in range(saves):
            # 循环使用已经种下来的 canvas；每次 clone 一份并 tweak title
            base = canvases[i % len(canvases)]
            snap = dict(base)
            snap["id"] = base["id"]  # 保持 id
            snap["title"] = f"{base['title']} · iter {i}"
            t0 = time.perf_counter()
            try:
                canvas_store.save_canvas(snap)
            except Exception:
                errors_bubbled += 1
                continue
            save_latency.append(time.perf_counter() - t0)

    stats = _percentiles(save_latency)

    return {
        "description": (
            "SHADOW_WRITE_CANVAS=true；save_canvas 循环 200 次；"
            "记录 P50/P95/P99；期望 P95 <= 500ms（治理方案 §PR-6 P1 硬约束）"
        ),
        "saves_attempted": saves,
        "saves_bubbled_error": errors_bubbled,
        "latency_ms": stats,
        "target_p95_ms": 500.0,
        "verdict": "PASS" if stats["p95_ms"] <= 500.0 and errors_bubbled == 0 else "FAIL",
    }


def _scenario_D_tx_fail_safe(
    canvas_dir: Path,
    canvases: list[dict[str, Any]],
    tx_fail_iters: int,
) -> dict[str, Any]:
    """场景 D：sqlite BEGIN EXCLUSIVE 锁 DB；测 shadow write fail-safe（异常不上抛）。"""

    from app.stores import canvas_store
    from tests.shadow_read._helpers import migrate_baseline

    migrate_baseline(canvas_dir.parent)

    # 找到 DB 路径 + 提前压一条 baseline row 避免"表空导致 SELECT 之外都没竞争"的误判
    import main

    db_path = main.DATA_DB_PATH

    # 先在无锁状态下 pre-warm 一次 shadow write 确保 canvases 表有行
    with _env_scope(
        {"SHADOW_WRITE_CANVAS": "true", "CANVAS_PRIMARY_WRITE": "json"}
    ):
        pre_warm = dict(canvases[0])
        pre_warm["title"] = "prewarm"
        canvas_store.save_canvas(pre_warm)

    lock_conn = sqlite3.connect(db_path, timeout=0.1, isolation_level=None)
    # 设短的 busy_timeout 让 shadow write 快速抢不到锁
    lock_conn.execute("PRAGMA busy_timeout = 200")

    save_bubbled_errors = 0
    saves_completed = 0
    per_iter_ms: list[float] = []

    try:
        lock_conn.execute("BEGIN EXCLUSIVE")
        with _env_scope(
            {"SHADOW_WRITE_CANVAS": "true", "CANVAS_PRIMARY_WRITE": "json"}
        ):
            for i in range(tx_fail_iters):
                snap = dict(canvases[(i + 1) % len(canvases)])
                snap["title"] = f"lockprobe iter {i}"
                t0 = time.perf_counter()
                try:
                    canvas_store.save_canvas(snap)
                    saves_completed += 1
                except Exception:
                    save_bubbled_errors += 1
                per_iter_ms.append((time.perf_counter() - t0) * 1000)
    finally:
        try:
            lock_conn.execute("COMMIT")
        except Exception:
            try:
                lock_conn.execute("ROLLBACK")
            except Exception:
                pass
        lock_conn.close()

    # 读回 shadow_diff/canvas_write/*.jsonl 看是否有 failure 记录
    diff_root = Path(main.DATA_DIR) / "shadow_diff" / "canvas_write"
    failure_records = 0
    sample_failure_reason: str | None = None
    if diff_root.exists():
        for f in diff_root.glob("*.jsonl"):
            for line in f.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except Exception:
                    continue
                failure_records += 1
                if sample_failure_reason is None:
                    sample_failure_reason = str(rec.get("error") or rec.get("fallback_reason"))

    # 验证：JSON 主写文件已被更新（因为 main.save_canvas 走 JSON 主写，不受锁影响）
    json_files_written = 0
    for c in canvases[1 : tx_fail_iters + 1]:
        p = canvas_dir / f"{c['id']}.json"
        if p.exists():
            content = json.loads(p.read_text(encoding="utf-8"))
            if content.get("title", "").startswith("lockprobe iter"):
                json_files_written += 1

    fail_safe_ok = save_bubbled_errors == 0 and saves_completed == tx_fail_iters
    return {
        "description": (
            "sqlite BEGIN EXCLUSIVE 持锁；shadow write 无法拿到写锁；"
            "验证 save_canvas 主路径（JSON）不受影响 + shadow_write 异常不上抛"
        ),
        "iterations": tx_fail_iters,
        "saves_completed_no_exception": saves_completed,
        "saves_bubbled_exception": save_bubbled_errors,
        "shadow_write_failure_records_logged": failure_records,
        "json_primary_write_files_actually_updated": json_files_written,
        "sample_failure_reason": sample_failure_reason,
        "per_iter_latency_ms": [round(x, 3) for x in per_iter_ms],
        "target_fail_safe": "save_bubbled_exception == 0 AND JSON files updated",
        "verdict": "PASS" if fail_safe_ok and json_files_written == tx_fail_iters else "FAIL",
    }


# ---------------------------------------------------------------------------
# top-level run
# ---------------------------------------------------------------------------


def run_probe(
    *,
    scale: int,
    seed: int,
    loads: int,
    saves: int,
    tx_fail_iters: int,
    tmp_path: Path,
) -> dict[str, Any]:
    rng = random.Random(seed)
    scenarios: dict[str, Any] = {}
    observations: list[dict[str, Any]] = []

    # --- Scenario A ---
    workspace_a = tmp_path / "scenA"
    workspace_a.mkdir()
    with _isolated_workspace(workspace_a):
        import main

        canvas_dir_a = Path(main.CANVAS_DIR)
        canvases_a = _seed_canvases_json(canvas_dir_a, random.Random(seed + 1), scale)
        scenarios["A_hit_rate"] = _scenario_A_hit_rate(
            canvas_dir_a, canvases_a, random.Random(seed + 2), loads=loads
        )

    # --- Scenario B ---
    workspace_b = tmp_path / "scenB"
    workspace_b.mkdir()
    with _isolated_workspace(workspace_b):
        import main

        canvas_dir_b = Path(main.CANVAS_DIR)
        canvases_b = _seed_canvases_json(canvas_dir_b, random.Random(seed + 3), scale)
        scenarios["B_diff_rate"] = _scenario_B_diff_rate(
            canvas_dir_b, canvases_b, random.Random(seed + 4), loads=loads
        )

    # --- Scenario C ---
    workspace_c = tmp_path / "scenC"
    workspace_c.mkdir()
    with _isolated_workspace(workspace_c):
        import main

        canvas_dir_c = Path(main.CANVAS_DIR)
        canvases_c = _seed_canvases_json(canvas_dir_c, random.Random(seed + 5), scale)
        scenarios["C_write_latency"] = _scenario_C_write_latency(
            canvas_dir_c, canvases_c, random.Random(seed + 6), saves=saves
        )

    # --- Scenario D ---
    workspace_d = tmp_path / "scenD"
    workspace_d.mkdir()
    with _isolated_workspace(workspace_d):
        import main

        canvas_dir_d = Path(main.CANVAS_DIR)
        canvases_d = _seed_canvases_json(
            canvas_dir_d, random.Random(seed + 7), max(scale, tx_fail_iters + 1)
        )
        scenarios["D_tx_fail_safe"] = _scenario_D_tx_fail_safe(
            canvas_dir_d, canvases_d, tx_fail_iters=tx_fail_iters
        )

    # --- observations / CB-P5-08 candidates ---
    # asymmetric normalizer: single-canvas JSON vs full-DB snapshot
    scen_a = scenarios["A_hit_rate"]
    if scen_a.get("records_with_missing_in_json_nonempty", 0) > 0:
        observations.append(
            {
                "cb_candidate": "CB-P5-08",
                "severity": "P2",
                "title": (
                    "shadow_read canvas normalizer 与 DB snapshot 结构非对称 · "
                    "每次 load 都把'DB 里其它 canvas'算作 missing_in_json"
                ),
                "detail": (
                    "app.shadow_read.runner._normalize_json_canvas 只返回"
                    " {loaded_id: {...}} 单元素 dict，而 _load_db_snapshot 返回"
                    "整表 rows。所以任一次 load_canvas 触发的 shadow_read 记录都会"
                    "把 '当前不是被 load 的 canvas' 全部记录到 missing_in_json——"
                    "这是 canvas 域独有的结构非对称（其它 4 个 domain load 的都是"
                    "整表/整集合）。不算数据丢失，但会给运维观察增加 O(N) 噪声，"
                    "降低 alert 信噪比。建议 Wave 3-K 承接：canvas 域"
                    "single-id load 时只比对'同一 legacy_id'的字段级差异，"
                    "或者在 shadow_read layer 里增加 'load_scope=single_id' 语义。"
                ),
                "evidence_key": "scenarios.A_hit_rate.records_with_missing_in_json_nonempty",
            }
        )

    # created_at/updated_at datatype drift (already documented in existing test)
    if scen_a["field_diff_count_stats"]["mean"] >= 1.0:
        observations.append(
            {
                "cb_candidate": "CB-P5-08",
                "severity": "P3",
                "title": (
                    "created_at/updated_at 类型转换稳定触发 field_diffs（既知）"
                ),
                "detail": (
                    "JSON epoch-ms int vs DB DateTime ISO 字符串。"
                    "tests/shadow_read/test_canvas_shadow.py:test_shadow_enabled_no_diff_when_db_matches "
                    "已经承认此行为不算失败。运维监控应把 field 名单里的 "
                    "created_at / updated_at 加白名单过滤，否则每一次 load "
                    "都会产生 field_diffs 记录。"
                ),
                "evidence_key": "scenarios.A_hit_rate.field_diff_count_stats",
            }
        )

    scen_d = scenarios["D_tx_fail_safe"]
    if scen_d["saves_bubbled_exception"] > 0:
        observations.append(
            {
                "cb_candidate": "CB-P5-08",
                "severity": "P0",
                "title": "shadow_write 失败隔离契约破裂",
                "detail": (
                    "sqlite BEGIN EXCLUSIVE 持锁时 canvas_store.save_canvas "
                    "上抛异常，与 P0 硬约束（shadow write 内部异常不冒泡到主"
                    "写路径）不符。"
                ),
                "evidence_key": "scenarios.D_tx_fail_safe.saves_bubbled_exception",
            }
        )

    if scen_d["json_primary_write_files_actually_updated"] != scen_d["iterations"]:
        observations.append(
            {
                "cb_candidate": "CB-P5-08",
                "severity": "P0",
                "title": "JSON 主写在 DB 锁竞争下未成功落盘",
                "detail": (
                    "sqlite BEGIN EXCLUSIVE 持锁时 JSON 主写文件更新数量与"
                    "迭代次数不匹配，说明主写路径受 DB 锁影响。"
                    "这与 CANVAS_PRIMARY_WRITE=json 模式下'主写和 DB 完全解耦'"
                    "的契约不符。"
                ),
                "evidence_key": "scenarios.D_tx_fail_safe.json_primary_write_files_actually_updated",
            }
        )

    # shadow write 在 DB 锁竞争下 stall 5s（busy_timeout=5000 PRAGMA）
    per_iter = scen_d.get("per_iter_latency_ms", [])
    if per_iter and max(per_iter) >= 4000:
        observations.append(
            {
                "cb_candidate": "CB-P5-08",
                "severity": "P1",
                "title": (
                    "DB 锁竞争下 save_canvas 每次 stall ~5s（shadow_write "
                    "busy_timeout PRAGMA 语义）"
                ),
                "detail": (
                    "app/db/engine.py 注入 `PRAGMA busy_timeout = 5000`；"
                    "shadow_write 在 DB 被 BEGIN EXCLUSIVE 锁定时会阻塞到 "
                    "busy_timeout 才 raise。JSON 主路径本身不受影响（异常已"
                    "隔离，未冒泡），但 save_canvas 的墙钟延迟 = JSON 主写 + "
                    "shadow_write 5s wait。这是 CANVAS_PRIMARY_WRITE=json 模式下"
                    "可接受的（毕竟异常不冒泡），但**切到 db 主写后，任何 DB "
                    "级锁竞争都会直接把 save_canvas 阻塞到 5s，用户可见回归"
                    "风险显著**。建议 Wave 3-K 承接 CANVAS_PRIMARY_WRITE=db "
                    "前：降低 canvas_writer 的 busy_timeout 到 500-1000ms + "
                    "把长时间锁竞争纳入 SLI/SLO 观察。"
                ),
                "evidence_key": "scenarios.D_tx_fail_safe.per_iter_latency_ms",
            }
        )

    # readiness verdict aggregation
    verdicts = {k: v["verdict"] for k, v in scenarios.items()}
    all_pass = all(v == "PASS" for v in verdicts.values())
    any_p0 = any(o.get("severity") == "P0" for o in observations)
    any_p1 = any(o.get("severity") == "P1" for o in observations)

    if any_p0:
        readiness = "RED"
    elif not all_pass or any_p1:
        readiness = "YELLOW"
    else:
        readiness = "GREEN"

    return {
        "schema": SCHEMA_VERSION,
        "synthetic_load_declaration": SYNTHETIC_DECLARATION,
        "generated_at_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        "scale": scale,
        "seed": seed,
        "loads_per_scenario": loads,
        "saves_scenario_C": saves,
        "tx_fail_iters_scenario_D": tx_fail_iters,
        "environment": _environment_fact_check(),
        "scenarios": scenarios,
        "scenario_verdicts": verdicts,
        "observations": observations,
        "readiness_verdict": readiness,
        "readiness_verdict_definition": {
            "GREEN": "所有 4 场景 PASS 且无 P0/P1 观察项 → 可放行 CANVAS_PRIMARY_WRITE=db",
            "YELLOW": "有 P1 观察项 或 部分场景 FAIL（无 P0）→ 有条件放行（先修 P1）",
            "RED": "存在 P0 观察项 → 不建议放行 db 主写",
        },
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


ALLOWED_SCALES = (10, 50, 200, 500)


def main_cli(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="synth_shadow_read_probe",
        description=(
            "Canvas shadow_read 就绪度合成负载评估探针（synthetic load only）"
        ),
    )
    parser.add_argument(
        "--scale",
        type=int,
        default=50,
        help=f"合成 canvas 数量（允许 {ALLOWED_SCALES}，默认 50）",
    )
    parser.add_argument(
        "--output",
        type=str,
        required=True,
        help="JSON 报告输出路径",
    )
    parser.add_argument("--seed", type=int, default=1337)
    parser.add_argument("--loads", type=int, default=100)
    parser.add_argument("--saves", type=int, default=200)
    parser.add_argument("--tx-fail-iters", type=int, default=3)
    args = parser.parse_args(argv)

    if args.scale not in ALLOWED_SCALES:
        parser.error(f"--scale must be one of {ALLOWED_SCALES}, got {args.scale}")

    # 用 tempfile 独立目录避免污染任何真实数据
    import tempfile
    import shutil

    tmp_dir = Path(tempfile.mkdtemp(prefix="synth_probe_"))
    try:
        report = run_probe(
            scale=args.scale,
            seed=args.seed,
            loads=args.loads,
            saves=args.saves,
            tx_fail_iters=args.tx_fail_iters,
            tmp_path=tmp_dir,
        )
    finally:
        # 清掉整个 tmp 工作区
        shutil.rmtree(tmp_dir, ignore_errors=True)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    # 简要打印
    print(f"[synth-probe] scale={args.scale} readiness={report['readiness_verdict']}")
    for k, v in report["scenario_verdicts"].items():
        print(f"  {k}: {v}")
    for obs in report["observations"]:
        print(
            f"  observation ({obs['severity']} · {obs['cb_candidate']}): "
            f"{obs['title']}"
        )
    print(f"[synth-probe] report -> {output_path}")

    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main_cli())
